spring:
  application:
    name: customers

server:
  port: ${customers.port:8081}

management:
  security:
    enabled: false

---
spring:
  profiles: eureka01

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka01:8761/eureka
  instance:
    hostname: eureka01
    instance-id: ${eureka.instance.hostname}:${spring.application.name}:${server.port}

---
spring:
  profiles: eureka02

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka02:8761/eureka
  instance:
    hostname: eureka02
    instance-id: ${eureka.instance.hostname}:${spring.application.name}:${server.port}
